name: eGt Current Tag

description: Get current tag name from `github.ref` environment variable

branding:
  icon: tag
  color: blue

outputs:
  image-tag:
    description: Tag name
    value: ${{ steps.get-tag.outputs.image-tag }}

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4
    - name: Set up docker image tag
      id: get-tag
      run: |
        echo "current push ref type: ${{ github.ref_type }}"
        if [ "${{ github.ref_type }}" = "tag" ]; then
            echo "image-tag=${{ github.ref_name }}" >> $GITHUB_OUTPUT
        else
            echo "image-tag=$(git log -n 1 --pretty=format:'%h' --abbrev=10)" >> $GITHUB_OUTPUT
        fi
