name: trigger by user

on:
  workflow_dispatch:
    inputs:
      image-name:
        description: "Name of the image to build"
        required: true
        type: string
      source-path:
        description: "Path to the source code"
        required: true
        type: choice
        options:
          - ./apps/admin-site/Dockerfile
          - ./apps/client-site/Dockerfile
      dockerhub:
        description: "Dockerhub registry"
        required: true
        type: string
  workflow_call:
    inputs:
      image-name:
        description: "Name of the image to build"
        required: true
        type: string
      source-path:
        description: "Path to the source code"
        required: true
        type: string
      dockerhub:
        description: "Dockerhub registry"
        required: true
        type: string
jobs:
  say_hello:
    runs-on: ubuntu-latest
    steps:
      - name: echo
        run: |
          echo Hi ${{ github.event.head_commit.message }} !!
