name: Test github action

on:
  push:
    branches:
      - main
jobs:
  test-env:
    runs-on: ubuntu-latest
    steps:
      - name: echo env
        run: |
          GIT_COMMIT=1234
          curl -H "Content-Type: application/json" -X POST '${{ secrets.HI }}' -d '{"cards":[{"header":{"title":"打包通知","subtitle":"1234"},"sections":[{"widgets":[{"textParagraph":{"text":"'${GIT_COMMIT}'"}}]}]}]}'
