name: Test github action

on:
  pull_request:
    branches:
      - main
    types: "closed"
    paths-ignore:
      - "**.md"
jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: say hello
        run: echo "hello"
