name: Test github action

on:
  push:
    branches:
      - main
env:
  ClientImageName: "gw-bpsp-client-web"
  AmdinImageName: "gw-bpsp-admin-web"
# jobs:
#   call-resuable:
#     uses: ./.github/workflows/some.yml
#     with:
#       config-path: $(ls)
jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v4
      - name: Hello world action step
        uses: gw-nickchen/google-chat-notification@v1.3
        id: hello
        with:
          api-url: ${{ secrets.GOOGLE_CHAT_BOT_API_URL }}
          title: 前端打包完成
          subtitle: "feat: test"
          contents: |
            <b>前台</b>: ${{env.ClientImageName}}:'${GIT_COMMIT}
            <b>後台</b>: ${{env.ClientImageName}}:'${GIT_COMMIT}
          action-page: "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
