name: Test github action

on:
  push:
    branches:
      - main
jobs:
  test-env:
    runs-on: ubuntu-latest
    steps:
      - name: echo env
        run: |
          curl -H "Content-Type: application/json" -X POST '${{ secrets.HI }}' \ 
          -d '{
            "cards": [
              {
                "header": {
                  "title": "打包通知",
                  "subtitle": "${{ github.event.issue.title }}"
                },
                "sections": [
                  {
                    "widgets": [
                      {
                        "textParagraph": {
                          "text": "Hi"
                        }
                      }
                    ]
                  }
                ]
              }
            ]
          }'
