name: Test github action

on:
  push:
    branches:
      - main
jobs:
  test-env:
    runs-on: ubuntu-latest
    steps:
      - name: echo env
        run: |
          curl -d '{"text":"hi"}' -H "Content-Type: application/json" -X POST ${{ secrets.HI }}
