name: Test github action

on:
  push:
    branches:
      - main
jobs:
  test-env:
    runs-on: ubuntu-latest
    steps:
      - name: echo env
        run: |
          GIT_COMMIT=1234
          curl -H "Content-Type: application/json" -X POST '${{ secrets.HI }}' -d '{"text":"'${{github.event.head_commit.message}}'"}}'
      - name: fail handl
        if: failure()
        run: |
          GIT_COMMIT=1234
          curl -H "Content-Type: application/json" -X POST '${{ secrets.HI }}' -d '{"text":"fail"}}'
