name: Test github action on pull request

on:
  push:
    tags:
      - "*"
    branches:
      - main
    # types: "closed"
env:
  IS_TAG: ${{ github.ref_type == 'tag' }}
jobs:
  # var-setup:
  #   runs-on: ubuntu-latest
  #   outputs:
  #     image-tag: ${{ steps.get-tag.outputs.image-tag }}
  #     api-env: ${{ steps.get-env.outputs.api-env }}
  #   steps:
  #     - uses: actions/checkout@v4
  #     - name: Setup tag name
  #       id: get-tag
  #       uses: ./.github/workflows/actions/getTag
  #     - name: Set up API env
  #       id: get-env
  #       run: |
  #         echo "api-env=${{ github.ref_type == 'tag' && 'prod' || 'uat' }}" >> $GITHUB_OUTPUT
  # release:
  #   needs: var-setup
  #   runs-on: ubuntu-latest
  #   name: release
  #   steps:
  #     - name: echo
  #       run: |
  #         echo ${{ needs.var-setup.outputs.api-env }}
  #         echo ${{ needs.var-setup.outputs.image-tag }}
  my-job:
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: "1234"
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Use action
        uses: ./.github/workflows/actions/build-image
