name: Test github action on pull request

on:
  pull_request:
    branches:
      - main
    # types: "closed"
jobs:
  send_message:
    runs-on: ubuntu-latest
    name: send google chat message
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: echo env
        run: |
          GIT_COMMIT=1234
          curl -H "Content-Type: application/json" -X POST '${{ secrets.GOOGLE_CHAT_BOT_API_URL }}' -d '{"cardsV2":[{"cardId":"createCardMessage","card":{"header":{"title":"前台web打包通知","subtitle":"${{github.event.pull_request.title}}"},"sections":[{"widgets":[{"textParagraph":{"text":"<b>前台</b>: hi"}},{"textParagraph":{"text":"<b>後台</b>: hi2"}},{"buttonList":{"buttons":[{"text":"github action","onClick":{"openLink":{"url":"${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"}}}]}}]}]}}]}'
      # - name: send message
      #   uses: gw-nickchen/google-chat-notification@v1
      #   with:
      #     api-url: ${{ secrets.GOOGLE_CHAT_BOT_API_URL }}
      #     title: 前端 bpsp web 打包完成通知
      #     subtitle: ${{github.event.pull_request.title}}
      #     contents: |
      #       <b>前台</b>: hi
      #       <b>後台</b>: hello
      #     action-page: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
