name: Test github action on pull request

on:
  # push:
  #   tags:
  #     - "*"
  #   branches:
  #     - main
  pull_request:
    branches:
      - main
    types: "closed"
jobs:
  my-job:
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: "1234"
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: echo
        run: echo "hello"
      # - name: Use action
      #   uses: ./.github/workflows/actions/build-image
      #   with:
      #     image-name: image-name
      #     tag: tag
      #     dockerfile-path: dockerfile-path
      #     dockerhub: dockerhub
      #     environment: environment
  # reuse:
  #   uses: ./.github/workflows/some.yml
  #   with:
  #     config-path: 1234
