name: Test

on:
  workflow_call:
    inputs:
      config-path:
        required: true
        type: string

jobs:
  reusable_workflow_job:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: echo
        id: echo1
        run: |
          echo ${{ inputs.config-path }}
          echo "commitHash2=${{ github.sha }}" >> $GITHUB_OUTPUT
      - name: echo 2
        id: echo2
        run: |
          echo ${{ inputs.config-path }}
          echo ${{ steps.echo1.outputs.commitHash2 }}
