name: Test

on:
  workflow_call:
    inputs:
      config-path:
        required: true
        type: string
    secrets:
      envPAT:
        required: true

jobs:
  reusable_workflow_job:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: echo
        run: |
          echo ${{ inputs.config-path }}
      - uses: actions/labeler@v4
        with:
          repo-token: ${{ secrets.envPAT }}
          configuration-path: ${{ inputs.config-path }}
